# Generated by Django 4.0.3 on 2022-04-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antaganize', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
