# Generated by Django 4.0.3 on 2022-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antaganize', '0002_delete_uploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_img', models.ImageField(upload_to='sources/')),
            ],
        ),
    ]
